### PR TITLE
setLocale exported from index (renamed from customLocale)

### PR DESCRIPTION
**Pull request by rosskevin**

### CODE REVIEW

**Comment by rosskevin** [comment]
@ctavan I did the full commitizen workflow.  Not sure if it was the doc generation or prettier, but there are more (generated) lines changed than I would expect.  So the next PR I would expect fewer since this should set a baseline.

**Comment by ctavan** [comment]
@rosskevin sorry for the delay.

I'd prefer not to have a changelog generated. The changelog already exists on the github release page: https://github.com/ctavan/jupp/releases

The CHANGELOG.md is a legacy that I'd rather like to drop.

**Comment by ctavan** [comment]
Would you mind removing the CHANGELOG.md altogether (and rebase onto the latest master)?

**Comment by ctavan** [comment]
@rosskevin btw, 👏  for including "BREAKING CHANGE" in the commit message 😃 .

**Comment by rosskevin** [comment]
@ctavan we have an error on the CI setup again:

```
The command "echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc" exited with 0.
0.50s$ yarn run semantic-release
yarn run v1.3.2
error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/build/ctavan/jupp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run semantic-release" exited with 1.
```

**Comment by ctavan** [comment]
Argh, that again. I hope I was able to fix it in master now. Can you rebase once again? Sorry for the hassle.

**Pull request closed without merging**
