### PR TITLE
Rename file for clarity and export setLocale from index

### PR DESCRIPTION
**Pull request by rosskevin**

### CODE REVIEW

**Comment by rosskevin** [comment]
@ctavan misconfiguration on travis?

```
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/npm/lib/config/core.js:418:13
    at String.replace (<anonymous>)
```

**Comment by ctavan** [comment]
@rosskevin yeah indeed, that seems to be a problem with the semantic-release setup and pull requests coming from forks. I'll try to fix it!

**Comment by ctavan** [comment]
I confused that a bit. `commitizen` is just a helper to produce these messages. The actual meaning of them in the context of `semantic-release` are described here: https://github.com/semantic-release/semantic-release#commit-message-format

**Comment by ctavan** [comment]
You can use `yarn commit` to call `commitizen`.

**Comment by rosskevin** [comment]
I'm going to re-submit this.  The prettier PR really made this one a mess, and it's simple.

**Pull request closed without merging**
